package tr.xyz.folder.config;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import java.awt.Color;
import java.awt.Insets;

import javax.swing.JCheckBox;
import javax.swing.JPanel;

public class Settings {

	private JCheckBox enable;

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
		panel1.setBackground(new Color(-2695453));
		enable = new JCheckBox();
		enable.setAlignmentX(1.0f);
		enable.setHorizontalAlignment(0);
		enable.setHorizontalTextPosition(11);
		enable.setLabel("Enable Kotlin Collapse");
		enable.setSelected(false);
		enable.setText("Enable Kotlin Collapse");
		enable.setToolTipText("Enable disable extension functions");
		enable.putClientProperty("hideActionText", Boolean.FALSE);
		panel1.add(enable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_NORTHWEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
	}

	private void createUIComponents() {
		// TODO: place custom component creation code here 
	}
}
